### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.AccessException
  commentId: T:Dropbox.Api.AccessException
  id: AccessException
  parent: Dropbox.Api
  children: []
  langs:
  - csharp
  - vb
  name: AccessException
  nameWithType: AccessException
  fullName: Dropbox.Api.AccessException
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/AccessException.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: AccessException
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/AccessException.cs
    startLine: 14
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nAn exception which is caused by account not having access to this endpoint.\n"
  example: []
  syntax:
    content: 'public sealed class AccessException : StructuredException<AccessError>'
    content.vb: >-
      Public NotInheritable Class AccessException
          Inherits StructuredException(Of AccessError)
  inheritance:
  - System.Object
  - Dropbox.Api.DropboxException
  - Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}
  inheritedMembers:
  - Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.ErrorResponse
  - Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.Message
  - Dropbox.Api.DropboxException.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
references:
- uid: Dropbox.Api
  commentId: N:Dropbox.Api
  name: Dropbox.Api
  nameWithType: Dropbox.Api
  fullName: Dropbox.Api
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.DropboxException
  commentId: T:Dropbox.Api.DropboxException
  parent: Dropbox.Api
  name: DropboxException
  nameWithType: DropboxException
  fullName: Dropbox.Api.DropboxException
- uid: Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}
  commentId: T:Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}
  parent: Dropbox.Api
  definition: Dropbox.Api.StructuredException`1
  name: StructuredException<AccessError>
  nameWithType: StructuredException<AccessError>
  fullName: Dropbox.Api.StructuredException<Dropbox.Api.Auth.AccessError>
  nameWithType.vb: StructuredException(Of AccessError)
  fullName.vb: Dropbox.Api.StructuredException(Of Dropbox.Api.Auth.AccessError)
  name.vb: StructuredException(Of AccessError)
  spec.csharp:
  - uid: Dropbox.Api.StructuredException`1
    name: StructuredException
    nameWithType: StructuredException
    fullName: Dropbox.Api.StructuredException
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Auth.AccessError
    name: AccessError
    nameWithType: AccessError
    fullName: Dropbox.Api.Auth.AccessError
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Dropbox.Api.StructuredException`1
    name: StructuredException
    nameWithType: StructuredException
    fullName: Dropbox.Api.StructuredException
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Auth.AccessError
    name: AccessError
    nameWithType: AccessError
    fullName: Dropbox.Api.Auth.AccessError
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.ErrorResponse
  commentId: P:Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.ErrorResponse
  parent: Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}
  definition: Dropbox.Api.StructuredException`1.ErrorResponse
  name: ErrorResponse
  nameWithType: StructuredException<AccessError>.ErrorResponse
  fullName: Dropbox.Api.StructuredException<Dropbox.Api.Auth.AccessError>.ErrorResponse
  nameWithType.vb: StructuredException(Of AccessError).ErrorResponse
  fullName.vb: Dropbox.Api.StructuredException(Of Dropbox.Api.Auth.AccessError).ErrorResponse
- uid: Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.Message
  commentId: P:Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}.Message
  parent: Dropbox.Api.StructuredException{Dropbox.Api.Auth.AccessError}
  definition: Dropbox.Api.StructuredException`1.Message
  name: Message
  nameWithType: StructuredException<AccessError>.Message
  fullName: Dropbox.Api.StructuredException<Dropbox.Api.Auth.AccessError>.Message
  nameWithType.vb: StructuredException(Of AccessError).Message
  fullName.vb: Dropbox.Api.StructuredException(Of Dropbox.Api.Auth.AccessError).Message
- uid: Dropbox.Api.DropboxException.ToString
  commentId: M:Dropbox.Api.DropboxException.ToString
  parent: Dropbox.Api.DropboxException
  name: ToString()
  nameWithType: DropboxException.ToString()
  fullName: Dropbox.Api.DropboxException.ToString()
  spec.csharp:
  - uid: Dropbox.Api.DropboxException.ToString
    name: ToString
    nameWithType: DropboxException.ToString
    fullName: Dropbox.Api.DropboxException.ToString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Dropbox.Api.DropboxException.ToString
    name: ToString
    nameWithType: DropboxException.ToString
    fullName: Dropbox.Api.DropboxException.ToString
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.StructuredException`1
  commentId: T:Dropbox.Api.StructuredException`1
  name: StructuredException<TError>
  nameWithType: StructuredException<TError>
  fullName: Dropbox.Api.StructuredException<TError>
  nameWithType.vb: StructuredException(Of TError)
  fullName.vb: Dropbox.Api.StructuredException(Of TError)
  name.vb: StructuredException(Of TError)
  spec.csharp:
  - uid: Dropbox.Api.StructuredException`1
    name: StructuredException
    nameWithType: StructuredException
    fullName: Dropbox.Api.StructuredException
  - name: <
    nameWithType: <
    fullName: <
  - name: TError
    nameWithType: TError
    fullName: TError
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Dropbox.Api.StructuredException`1
    name: StructuredException
    nameWithType: StructuredException
    fullName: Dropbox.Api.StructuredException
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TError
    nameWithType: TError
    fullName: TError
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.StructuredException`1.ErrorResponse
  commentId: P:Dropbox.Api.StructuredException`1.ErrorResponse
  name: ErrorResponse
  nameWithType: StructuredException<TError>.ErrorResponse
  fullName: Dropbox.Api.StructuredException<TError>.ErrorResponse
  nameWithType.vb: StructuredException(Of TError).ErrorResponse
  fullName.vb: Dropbox.Api.StructuredException(Of TError).ErrorResponse
- uid: Dropbox.Api.StructuredException`1.Message
  commentId: P:Dropbox.Api.StructuredException`1.Message
  name: Message
  nameWithType: StructuredException<TError>.Message
  fullName: Dropbox.Api.StructuredException<TError>.Message
  nameWithType.vb: StructuredException(Of TError).Message
  fullName.vb: Dropbox.Api.StructuredException(Of TError).Message
shouldSkipMarkup: true
