### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.TfaAddExceptionDetails
  commentId: T:Dropbox.Api.TeamLog.TfaAddExceptionDetails
  id: TfaAddExceptionDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor
  langs:
  - csharp
  - vb
  name: TfaAddExceptionDetails
  nameWithType: TfaAddExceptionDetails
  fullName: Dropbox.Api.TeamLog.TfaAddExceptionDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaAddExceptionDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: TfaAddExceptionDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaAddExceptionDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Added members to two factor authentication exception list.</p>\n"
  example: []
  syntax:
    content: 'public class TfaAddExceptionDetails : object'
    content.vb: >-
      Public Class TfaAddExceptionDetails
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor
  commentId: M:Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.TfaAddExceptionDetails
  langs:
  - csharp
  - vb
  name: TfaAddExceptionDetails()
  nameWithType: TfaAddExceptionDetails.TfaAddExceptionDetails()
  fullName: Dropbox.Api.TeamLog.TfaAddExceptionDetails.TfaAddExceptionDetails()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaAddExceptionDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaAddExceptionDetails.cs
    startLine: 33
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.TfaAddExceptionDetails\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public TfaAddExceptionDetails()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.TfaAddExceptionDetails
  commentId: T:Dropbox.Api.TeamLog.TfaAddExceptionDetails
  parent: Dropbox.Api.TeamLog
  name: TfaAddExceptionDetails
  nameWithType: TfaAddExceptionDetails
  fullName: Dropbox.Api.TeamLog.TfaAddExceptionDetails
- uid: Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.TfaAddExceptionDetails.#ctor
  name: TfaAddExceptionDetails
  nameWithType: TfaAddExceptionDetails.TfaAddExceptionDetails
  fullName: Dropbox.Api.TeamLog.TfaAddExceptionDetails.TfaAddExceptionDetails
shouldSkipMarkup: true
